#include "citation.h"

#include <cstdlib>
#include <fstream>
#include <iostream>

namespace
{
    // The citation text. References checked against Crossref and the
    // Martinez group's TeraChem citation request (2026-09-30).
    const char *CITATION_TEXT =
        "AutoParams -- citation information\n"
        "The parameters in this directory were generated by AutoParams; the partial\n"
        "charges are a RESP fit to an electrostatic potential computed with TeraChem.\n"
        "If you use them in published work, please cite:\n"
        "\n"
        "AutoParams\n"
        "  M. A. Hix and A. R. Walker, \"AutoParams: An Automated Web-Based Tool To\n"
        "  Generate Force Field Parameters for Molecular Dynamics Simulations\",\n"
        "  J. Chem. Inf. Model. 63, 6293-6301 (2023). doi:10.1021/acs.jcim.3c01049\n"
        "\n"
        "TeraChem (RESP electrostatic potential; -o/--optimize geometry optimization)\n"
        "  I. S. Ufimtsev and T. J. Mart\xC3\xADnez, \"Quantum Chemistry on Graphical\n"
        "  Processing Units. 1. Strategies for Two-Electron Integral Evaluation\",\n"
        "  J. Chem. Theory Comput. 4, 222-231 (2008). doi:10.1021/ct700268q\n"
        "  I. S. Ufimtsev and T. J. Mart\xC3\xADnez, \"Quantum Chemistry on Graphical\n"
        "  Processing Units. 2. Direct Self-Consistent-Field Implementation\",\n"
        "  J. Chem. Theory Comput. 5, 1004-1015 (2009). doi:10.1021/ct800526s\n"
        "  I. S. Ufimtsev and T. J. Mart\xC3\xADnez, \"Quantum Chemistry on Graphical\n"
        "  Processing Units. 3. Analytical Energy Gradients, Geometry Optimization,\n"
        "  and First Principles Molecular Dynamics\", J. Chem. Theory Comput. 5,\n"
        "  2619-2628 (2009). doi:10.1021/ct9003004\n"
        "  S. Seritan et al., \"TeraChem: A graphical processing unit-accelerated\n"
        "  electronic structure package for large-scale ab initio molecular\n"
        "  dynamics\", WIREs Comput. Mol. Sci. 11, e1494 (2021). doi:10.1002/wcms.1494\n"
        "\n"
        "RESP charge fitting\n"
        "  C. I. Bayly, P. Cieplak, W. Cornell and P. A. Kollman, \"A well-behaved\n"
        "  electrostatic potential based method using charge restraints for deriving\n"
        "  atomic charges: the RESP model\", J. Phys. Chem. 97, 10269-10280 (1993).\n"
        "  doi:10.1021/j100142a004\n";

    std::string g_note;     // the closing line
    std::string g_logfile;  // autoparams.NNNN.out

    void announce_citation_file()
    {
        std::cout << g_note << std::endl;
        std::ofstream log(g_logfile, std::ios::app);
        if (log.is_open()) log << g_note << "\n";
    }
}

void write_citation_file(const Settings &settings)
{
    // Purpose: write <job_dir>/citation.txt and register the closing
    //   "Citation details: see ..." line, printed when the process exits
    //   (normally or through exit()), so it is the last line of the run.
    // Inputs: settings -- job_dir (absolute, with a trailing '/') and
    //   outfile (the run's .out log).
    // Returns/Outputs: none. A file that cannot be written is logged as an
    //   error but does not stop the run.
    std::string path = settings.job_dir + "citation.txt";
    std::ofstream out(path, std::ios::out | std::ios::trunc);
    if (out.is_open()) out << CITATION_TEXT;
    out.close();
    if (!out)
    {
        std::cerr << "ERROR: could not write " << path << std::endl;
        return;
    }
    // "autoparams.NNNN/citation.txt", relative to the directory the run
    // was started in (job_dir is <cwd>/autoparams.NNNN/).
    std::string dir = settings.job_dir;
    while (!dir.empty() && dir.back() == '/') dir.pop_back();
    std::string rel = dir.substr(dir.find_last_of('/') + 1) + "/citation.txt";
    g_note = "Citation details: see " + rel;
    g_logfile = settings.outfile;
    std::atexit(announce_citation_file);
}
